#!/usr/bin/env bash
#name=$(logname)
#MGMT_PATH=/etc/sudoers.d/photos
#CMD="/usr/bin/tmutil, /usr/sbin/softwareupdate, /usr/bin/pmset"
#SUDOERS="$name ALL = (ALL) NOPASSWD: $CMD"
#touch $MGMT_PATH
#todo: sudoers.d must be modified, might be easier with python
#python read, modify/add and write back in the file at the same place.
#syntax: python /path/to/file
#sudo chown -R root $MGMT_PATH
#sudo chmod -R 755 $MGMT_PATH
#sudo echo "$SUDOERS" > $MGMT_PATH
#echo "$SUDOERS"
plist_path="/etc/photo_mgmt/plist/photos.plist"
plist_filename=$(basename "$plist_path")
install_path="/Library/LaunchDaemons/$plist_filename"





echo "installing launchctl plist: $plist_path --> $install_path"
sudo cp -f "$plist_path" "$install_path"

sudo chown root "$install_path"
sudo chmod 644 "$install_path"

sudo launchctl unload "$install_path"
sudo launchctl load "$install_path"

echo "to check if it's running, run this command: sudo launchctl list | grep mgmt"
echo "to uninstall, run this command: sudo launchctl unload \"$install_path\""